name: dl
channels:
- soumith
- defaults
dependencies:
- appnope=0.1.0=py36_0
- bleach=1.5.0=py36_0
- cffi=1.10.0=py36_0
- cycler=0.10.0=py36_0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- freetype=2.5.5=2
- html5lib=0.999=py36_0
- icu=54.1=0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jbig=2.1=0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.0.1=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- markupsafe=0.23=py36_2
- matplotlib=2.0.2=np113py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.1=0
- nbconvert=5.2.1=py36_0
- nbformat=4.3.0=py36_0
- notebook=5.0.0=py36_0
- numpy=1.13.0=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pandocfilters=1.4.1=py36_0
- path.py=10.3.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.1.1=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.1=py36_0
- pycparser=2.17=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=2
- qtconsole=4.3.0=py36_0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.18=0
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pytorch=0.1.12=py36_2cu75
- torchvision=0.1.8=py36_2
- pip:
  - awscli==1.11.99
  - botocore==1.5.62
  - colorama==0.3.7
  - docutils==0.13.1
  - ipython-genutils==0.2.0
  - jmespath==0.9.3
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
  - protobuf==3.3.0
  - rsa==3.4.2
  - s3transfer==0.1.10
  - tensorflow==1.1.0
  - torch==0.1.12.post2
  - werkzeug==0.12.2
prefix: /Users/kdubovikov/miniconda3/envs/dl

